config/routes.rb
WatchMe::Application.routes.draw do

  get 'settings/update'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  post '/notify' => 'notify#handle'
  get '/notify' => 'notify#handle'
  
  get '/publish' => 'streams#info', as: 'publish'
  get '/publish/fmle.xml' => 'streams#fmle', as: 'fmle'
  
  
  get '/:id/popout' => 'streams#popout', as: 'stream_popout'
  get '/streams/:id/popout' => 'streams#popout'
  
  get '/vod/:name' => 'vods#index', as: 'vod'
  get '/vod/:name/:id' => 'vods#show', as: 'vod_show'
  
  get '/streams' => 'streams#index'
  get '/:id' => 'streams#show', :as => 'stream'
  patch '/:id' => 'streams#update'
  put '/:id' => 'streams#update'
  
  post '/settings/color' => 'settings#color'
  
  get '/lastfm/:id' => 'lastfm#playing'
  
  resources :messages, only: [:create]
  resources :streams
  
  root 'home#index'

end

app/models/stream.rb
class Stream < ActiveRecord::Base

  extend FriendlyId
  include Bootsy::Container
  
  mount_uploader :placeholder, PlaceholderUploader
  
  validates_presence_of :name
  validates_presence_of :description
  
  belongs_to :user
  has_many :messages
  delegate :username, to: :user
    
  friendly_id :username, use: :slugged
  
  has_many :vods
  has_many :subscriptions
  
  def markdown
    Kramdown::Document.new(body).to_html.html_safe
  end
  
  def go_live(client_id, client_ip)
    self.live = true
    self.viewers = 0
    self.client_id = client_id
    self.client_ip = client_ip
    save
  end
  
  def go_dark
    self.live = false
    self.viewers = 0
    save
  end
  
  def add_viewer
    self.viewers += 1
    save
  end
  
  def remove_viewer
    self.viewers -= 1
    save
  end

end

app/controllers/streams_controller.rb
require 'securerandom'
class StreamsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :popout]
  before_action :authenticate_stream!, only: [:update]

  def index
    @streams = Stream.all
  end

  def new
    if current_user.stream
      redirect_to current_user.stream
    end
    @stream = Stream.new
  end
  
  def create
    @stream = Stream.new(
      user: current_user,
      name: stream_params[:name],
      description: stream_params[:description],
      body: stream_params[:body]
    )
    @stream.public_key = SecureRandom.hex(6)
    @stream.private_key = SecureRandom.hex(12)
    @stream.user_id = current_user.id
    if @stream.save
      redirect_to @stream
    else
      render action: 'new'
    end
  end
  
  def edit
    @stream = current_user.stream
  end
  
  def update
    @stream = current_user.stream
    if @stream.update(stream_params)
      respond_to do |format|
        format.html { redirect_to @stream, success: 'Your stream was successfully updated.' }
        format.json { render :json => {  name: @stream.name, body: @stream.markdown, markdown: @stream.body  } }
      end
      Danthes.publish_to(
        "/stream/#{@stream.id}",
        type: 'info_update',
        stream: { name: @stream.name, description: @stream.description, markdown: @stream.markdown }
      )
    else
      render action: 'edit'
    end
  end
  
  def info
    @stream = current_user.stream
  end
  
  def fmle
    @stream = current_user.stream
    response.headers['Content-Disposition'] = "attachment; filename=watchmeio-#{current_user.username}-fmle.xml"
    render :layout => false
  end
  
  def popout
    @stream = Stream.friendly.find(params[:id])
    render :layout => false
  end

  def show
    @stream = Stream.friendly.find(params[:id])
    @owned = user_signed_in? && (current_user.try(:stream) === @stream)
    
    # mute the stream if we're live
    if @owned && @stream.live
      current_user.settings(:player).volume = 0
    end
    if user_signed_in?
      gon.push({ user: {
          color: current_user.settings(:chat).color,
          username: current_user.username
        }
      })
    end
    gon.push({
      streamer: @stream.user.id,
      stream_id: @stream.id,
      stream_name: @stream.name
    })
  end
  
  def player
    @stream = Stream.friendly.find(params[:id])
    gon.push({
      stream_id: @stream.id,
      stream_name: @stream.name
    })
    render :partial => 'player', :content_type => 'text/html'
  end
  
  def subscribe
    @stream = Stream.find(params[:id])
    sub = Subscription.new(user: current_user, stream: @stream)
  end

  private
  
  def authenticate_stream!
    @stream = Stream.friendly.find(params[:id])
    if current_user.stream != @stream then
      
      respond_to do |format|
        format.html { render text: 'Unauthorized!' }
        format.json { render :json => {error: 'Unauthorized!'} }
      end
    end
  end
  
  def stream_params
    params.require(:stream).permit(:name, :description, :body, :bootsy_image_gallery_id, :placeholder)
  end

end

app/views/streams/_chat.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Live Chat
    <% if user_signed_in? %>
      <span class="float-right">
        <select id="name_color">
          <% Settings.chat.colors.each do |color| %>
            <option value="<%=color%>" data-color="#<%=color%>" <%=( current_user.settings(:chat).color == color ? 'selected="selected"' : '')%>></option>
          <% end %>
        </select>
      </span>
    <% end %>
  </div>
  <div id="chat_panel">
    <div id="chat" class="panel-body chat">
      <% @stream.messages.limit(15).order(created_at: :desc).reverse.each do |message| %>
        <div class="message">
          <span class="body">
          <span class="name color-<%=message.user.settings(:chat).color%><%=( user_signed_in? && message.user === current_user ? ' myself' : '' )%>"><%= message.user.username %>:</span>
          <%= message.message.emojify.html_safe %> 
          </span>
        </div>
      <% end %>
    </div>
    <div class="chat_input">
      <% if user_signed_in? %>
        <%= form_for @stream.messages.new do |f| %>
          <%= f.hidden_field :stream_id %>
          <%= f.text_area :message, class: 'form-control no-autocomplete', rows: 1 %>
        <% end %>
      <% else %>
        <div class="cant-chat">
          <%= link_to 'Login', new_user_session_path %> or <%= link_to 'register', new_user_registration_path %> to chat.
        </div>
      <% end %>
    </div>
  </div>
</div>
<script id="message_tpl" type="x-tmpl-mustache">
  <div id="msg_{{id}}" data-user-id="{{user_id}}" data-id="{{id}}" class="message">
    <span class="body">
      <span class="name {{myself}}" style="color:#{{color}};">{{username}}:</span>
      {{{message}}}</span>
  </div>
</script>

app/views/streams/_form.html.haml
= form_for @stream , :html => {:multipart => true} do |f|
  - if @stream.errors.any?
    - @stream.errors.full_messages.each do |msg|
      .alert.alert-danger= msg
  .row
    .col-xs-12.col-md-6.col-lg-6
      .form-group
        = f.label :name, 'Broadcast Name'
        = f.text_field :name, class: 'form-control'
    .col-xs-12.col-md-6.col-lg-6
      .form-group
        = f.label :description, 'Broadcast Description'
        = f.text_field :description, class: 'form-control'
  .row
    .col-xs-12.col-md-12.col-lg-12
      .form-group
        .wmd-panel
          #wmd-button-bar
          = f.text_area :body, class: 'form-control wmd-input', id: 'pagedown-textarea', rows: '10'
  %hr
  .row
    .col-xs-12.col-md-6.col-lg-6
      %div= f.label :placeholder
      %span.btn.btn-default.btn-file
        Upload Placeholder
        = f.file_field :placeholder
      .small
        Upload a placeholder image that will be displayed when you are not streaming.
    .col-xs-hidden.col-md-6.col-lg-6
      = image_tag @stream.placeholder_url(:thumb)
  %hr
  .row
    .col-xs-12.col-md-6.col-lg-3
      = f.submit 'Save Changes', class: 'btn btn-primary'

app/views/streams/_player.html.erb
<% if @stream.live? %>
  <% if params[:tech] && (['dash', 'flash', 'hds', 'hls', 'hlsn'].include? params[:tech]) %>
    <%= render 'streams/players/' + params[:tech] %>
  <% else %>
    <% if user_signed_in? %>
      <%= render 'streams/players/' + current_user.settings(:player).tech %>
    <% else %>
      <%= render 'streams/players/' + Settings.player.tech %>
    <% end %>
  <% end %>
<% else %>
  <%= render 'streams/players/offline' %>
<% end %>
<script id="html5v_tpl" type="x-tmpl-mustache">
  <video id="html5_player" poster="<%= Settings.rtmp.proto %>://<%= Settings.rtmp.server %><%= Settings.rtmp.post %>/jpg/{{ username }}.jpg" controls="true" autoplay="true">
    <source src="<%= Settings.rtmp.proto %>://<%= Settings.rtmp.server %><%= Settings.rtmp.post %>/hls/{{ username }}/index.m3u8" type="application/x-mpegURL"></source>
  </video>
</script>
<script type="text/javascript" charset="utf-8">
  var orig_h = 433;
  $(window).resize(function() {
    if($('#stream_container').parent().width() < 617) {
      $('#stream_container').css('height', $('#stream_container').parent().width() / 1.78 + 'px');
      $('#player').css('height', $('#player').parent().parent().width() / 1.78 + 'px');
    }
    else {
      $('#stream_container').css('height', orig_h + 'px');
      $('#player').css('height', orig_h + 'px');
    }
    $('#stream_container').css('width', $('#stream_container').parent().width() + 'px');
    $('#player').css('width', $('#player').parent().parent().width() + 'px');
  });
  var popUp = null;
  function popout() {
    popUp = window.open(
      '<%= stream_popout_path(@stream) %>',
      'targetWindow',
      'toolbar=no,location=no,status=no,menubar=no,scrollbars=no,resizable=yes,width=853,height=480'
    );
    popUp.onunload = function() {
      setTimeout(function(){
        if (popUp.closed) {
          player.play2();
        }
      }, 50);
    }
    player.pause();
    return false;
  }
</script>

app/views/streams/_player_popout.html.erb
<% if @stream.live? %>
  <% if user_signed_in? %>
    <%= render 'streams/players/' + current_user.settings(:player).tech %>
  <% else %>
    <%= render 'streams/players/hls' %>
  <% end %>
<% else %>
  <%= render 'streams/players/offline' %>
<% end %>
<script type="text/javascript" charset="utf-8">
  
</script>

app/views/streams/edit.html.haml
%h2 Edit Stream Details
= render 'form'

app/views/streams/fmle.html.erb
<flashmedialiveencoder_profile>
  <preset>
    <name>watchme.IO</name>
    <description>watchme.IO - <%= current_user.username %></description>
  </preset>
  <encode>
    <video>
      <format>H.264</format>
      <datarate>1200</datarate>
      <outputsize>1280x720</outputsize>
    </video>
  </encode>
  <output>
    <rtmp>
      <url><%= 'rtmp://' + Settings.rtmp.server + '/' + Settings.rtmp.app %></url>
      <stream><%= current_user.username + '?key=' + @stream.private_key %></stream>
    </rtmp>
  </output>
</flashmedialiveencoder_profile>

app/views/streams/index.html.erb
<% @streams.each do |stream| %>
<div class="col-md-4 stream-block">
  <%= link_to stream_path(stream)  do %>
    <div class="stream_image" style="background-image: url('<%= (stream.live ? Settings.rtmp.proto + '://' + Settings.rtmp.server + Settings.rtmp.post + '/jpg/' + stream.user.username.downcase + '_small.jpg' : stream.placeholder_url) %>');"></div>
  <% end %>
  <% if stream.live %>
    <div class="live-tag"><span class="glyphicon glyphicon-facetime-video live-dot"></span>Live</div>
  <% end %>
  <h3><%= link_to stream.name, stream %></h3>
</div>
<% end %>

app/views/streams/info.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12 col-lg-6">
    <h3>Encoder Requirements</h3>
    <p>
      For the best streaming quality and experience, we
      <strong>
        highly
      </strong>
      recommend the following encoder settings.
      <hr />
      <div class="fixed">
        x264 baseline CBR (1500kbit/s) @ 1280x720 - 96kbit/s AAC Audio
      </div>
      <hr />
      <ul>
        <li>
          x264 / h264 encoder
          <ul>
            <li>baseline profile</li>
            <li>constant bitrate</li>
            <li>25 fps</li>
            <li>key frame every 2 seconds (50 frames)</li>
          </ul>
        </li>
        <li>
          AAC Audio
          <ul>
            <li>96 kbit/s</li>
            <li>44.100 kHz</li>
          </ul>
        </li>
      </ul>
    </p>
  </div>
  <div class="col-xs-12 col-md-12 col-lg-6">
    <h3>RTMP Details</h3>
    <p>
      <div class="server">
        <strong>Server:</strong>
        <span class="fixed"><%= Settings.rtmp.server %></span>
      </div>
      <div class="server">
        <strong>App:</strong>
        <span class="fixed"><%= Settings.rtmp.app %></span>
      </div>
      <div class="server">
        <strong>URL:</strong>
        <span class="fixed">rtmp://<%= Settings.rtmp.server %>/<%= Settings.rtmp.app %></span>
      </div>
      <div class="server">
        <strong>Key:</strong>
        <span id="key-toggle" class="fixed">Click to show</span>
        <span id="key" class="fixed"><%= @stream.slug + '?key=' + @stream.private_key %></span>
      </div>
    </p>
    <hr />
    <%= link_to 'Download Flash Media Live Encoder XML', fmle_path, class: 'btn btn-primary' %>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
  function selectText(element) {
      var doc = document
          , text = doc.getElementById(element)
          , range, selection
      ;    
      if (doc.body.createTextRange) { //ms
          range = doc.body.createTextRange();
          range.moveToElementText(text);
          range.select();
      } else if (window.getSelection) { //all others
          selection = window.getSelection();        
          range = doc.createRange();
          range.selectNodeContents(text);
          selection.removeAllRanges();
          selection.addRange(range);
      }
  }
  $(document).ready(function(){
    $('#key-toggle').click(function(){
      $('#key-toggle').hide();
      $('#key').show();
      selectText('key');
    });
    $('#key').click(function(){
      $('#key').hide();
      $('#key-toggle').show();
    });
  });
</script>

app/views/streams/new.html.haml
%h2 Create Your Stream
= render 'form'

app/views/streams/popout.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>watchme.io - <%= @stream.name %></title>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag "streams" %>
    <style type="text/css" media="screen">
      html, body {
        background-color: #000;
        margin: 0 !important;
        padding: 0 !important;
        height: 100% !important;
        width: 100% !important;
      }
      #stream_container {
        margin: 0px;
        height: 100% !important;
        width: 100% !important;
      }
      #player {
        width: 100%;
        min-height: 100%;
      }
    </style>
</head>
<body>
  <div id="stream_container">
      <div id="player">
        <%= render 'streams/player_popout' %>
      </div>
  </div>
</body>
</html>

app/views/streams/show.html.erb
<div id="<%= dom_id @stream %>">
  <div class="row">
    <div class="col-xs-12 cold-md-12 col-lg-12 header">
      <% if @owned %>
        <h3><span class="rest-in-place" data-attribute="name" id="stream_name"><%= @stream.name %></span></h3>
      <% else %>
        <h3><span id="stream_name"><%= @stream.name %></span></h3>
      <% end %>
    </div>
  </div>
  
  <div class="row">
  
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
  
      <div id="stream_container">
        <div class="player-popout">
          <a href="#" onclick="return popout();"><span class="glyphicon glyphicon-new-window"></span></a>
        </div>
        <div id="player_updater">
          <div id="player">
            <%= render 'streams/player' %>
          </div>
        </div>
      </div>
      
      <% if @stream.user.settings(:lastfm).enabled %>
      <% if LastFm.nowplaying(@stream.user.settings(:lastfm).username).try(:playing) %>
        <div id="lastfm">
      <% else %>
        <div id="lastfm" style="display: none;">
      <% end %>
          <div class="lastfm_info">
            <div class="lastfm_img" id="lastfm_img"></div>
            <div class="lastfm_song" data-link="" id="lastfm_song">Loading ...</div>
            <div class="lastfm_artist" data-link="" id="lastfm_artist">Loading ...</div>
          </div>
          <div id="amazonref" class="amazonref" data-link="" style="display:none;"></div>
          <div id="spotifyopen" class="spotifyopen" data-link="" style="display:none;"></div>
        </div>
       
      <% end %>
      
    </div>
  
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 chat-pad">
      <%= render 'streams/chat' %>
    </div>
  </div>
  
  <div class="row">
    <!-- stats --> 
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
      <div class="panel panel-default">
        <div class="panel-heading">
          Channel Info
        </div>
        <div class="panel-body">
          <% if @owned %>
            <textarea id="stream_markdown" style="display:none;"><%= @stream.body %></textarea>
            <span class="rest-in-place" data-formtype="markdown" data-attribute="body" id="stream_body"><%= @stream.markdown %></span>
          <% else %>
            <span id="stream_body"><%= @stream.markdown %></span>
            
          <% end %>
        </div>
      </div>
    </div>
    <!-- info --> 
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <div class="panel panel-default">
        <div class="panel-heading">
          Channel Stats
        </div>
        <div class="panel-body">
          <div>
            <strong>Viewers:</strong> <span id="viewers"><%= ( @stream.viewers >= 1 ? @stream.viewers : 'Offline' ) %></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <%= subscribe_to "/stream/#{@stream.id}" %>
</div>