config/routes.rb
WatchMe::Application.routes.draw do

  get 'settings/update'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  post '/notify' => 'notify#handle'
  get '/notify' => 'notify#handle'
  
  get '/publish' => 'streams#info', as: 'publish'
  get '/publish/fmle.xml' => 'streams#fmle', as: 'fmle'
  
  
  get '/:id/popout' => 'streams#popout', as: 'stream_popout'
  get '/streams/:id/popout' => 'streams#popout'
  
  get '/vod/:name' => 'vods#index', as: 'vod'
  get '/vod/:name/:id' => 'vods#show', as: 'vod_show'
  
  get '/streams' => 'streams#index'
  get '/:id' => 'streams#show', :as => 'stream'
  patch '/:id' => 'streams#update'
  put '/:id' => 'streams#update'
  
  post '/settings/color' => 'settings#color'
  
  get '/lastfm/:id' => 'lastfm#playing'
  
  resources :messages, only: [:create]
  resources :streams
  
  root 'home#index'

end

app/models/vod.rb
class Vod < ActiveRecord::Base
  
  belongs_to :stream
  
end

app/controllers/vods_controller.rb
class VodsController < ApplicationController
  
  def index
    @vods = Stream.friendly.find(params[:name]).vods
  end
  
  def show
    @vods = Stream.friendly.find(params[:name]).vods
    @vod = @vods.find(params[:id])
  end
  
end

app/views/vods/index.html.erb
<% @vods.each do |vod| %>
<div class="col-md-4 stream-block">
  <%= link_to vod_show_path(vod.stream.friendly_id, vod.id) do %>
    <div class="stream_image" style="background-image: url('<%= Settings.rtmp.proto %>://<%= Settings.rtmp.outgest %><%= Settings.rtmp.post %>/jpg/<%= vod.basename %>_small.jpg');">
    </div>
  <% end %>
  <h3><%= link_to vod.title, vod_show_path(vod.stream.friendly_id, vod.id)  %></h3>
</div>
<% end %>

app/views/vods/show.html.erb
<div class="row">

  <!-- left --> 
  <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
    <!-- player --> 
    <div id="stream_container">
      <div id="player">
        <video style="height: 433px; width: 770px;" src="http://<%= Settings.rtmp.server %>/vod/<%= @vod.basename %>.mp4" controls="true"></video>
      </div>
    </div>
  </div>
  
  <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
    <h3><%= @vod.title %></h3>
    <p><%= @vod.description %></p>
  </div>

</div>

<script type="text/javascript" charset="utf-8">
$(document).ready(function(){

  var parameters = {
    poster: "<%= '/preview/' + @vod.basename + '.jpg' %>",
  <% if params[:mp4] %>
    src: "http://<%= Settings.rtmp.server %>/mp4/<%= @vod.basename %>.mp4",
    optimizeBuffering : true,
    optimizeInitialIndex: true,
  <% else %>
    src: "rtmp://<%= Settings.rtmp.server %>/vod/<%= @vod.basename %>.mp4",
    optimizeBuffering : false,
    optimizeInitialIndex: false,
  <% end %>
    autoPlay: 'false',
    controlBarAutoHide: true,
    controlBarAutoHideTimeout: 1,
    playButtonOverlay: true,
    streamType: "recorded",
  };
  swfobject.embedSWF(
    "/StrobeMediaPlayback.swf",
    "player",
    770,
    433,
    "10.1.0",
    "/expressInstall.swf",
    parameters,
    { allowFullScreen: "true", allowScriptAccess: 'always', wmode: 'opaque' },
    { name: "player" }
  );
});
</script>