config/routes.rb
WatchMe::Application.routes.draw do

  get 'settings/update'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  devise_for :users
  
  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy'
  end
  
  post '/notify' => 'notify#handle'
  get '/notify' => 'notify#handle'
  
  get '/publish' => 'streams#info', as: 'publish'
  get '/publish/fmle.xml' => 'streams#fmle', as: 'fmle'
  
  
  get '/:id/popout' => 'streams#popout', as: 'stream_popout'
  get '/streams/:id/popout' => 'streams#popout'
  
  get '/vod/:name' => 'vods#index', as: 'vod'
  get '/vod/:name/:id' => 'vods#show', as: 'vod_show'
  
  get '/streams' => 'streams#index'
  get '/:id' => 'streams#show', :as => 'stream'
  patch '/:id' => 'streams#update'
  put '/:id' => 'streams#update'
  
  post '/settings/color' => 'settings#color'
  
  get '/lastfm/:id' => 'lastfm#playing'
  
  resources :messages, only: [:create]
  resources :streams
  
  root 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <title>watchme.IO</title>
    <%= stylesheet_link_tag "application", media: "all" %>
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= yield :javascript_includes %>
    <%= include_gon watch: true %>
    <%= javascript_include_tag "application" %>
  </head>
  <body data-controller="<%= controller_path %>" data-action="<%= action_name %>">
    <!-- Fixed navbar -->
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'watchme.I/O', root_path, class: 'navbar-brand fixed' %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Streams', streams_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <% if current_user.stream %>
                <li><%= link_to 'My Stream', stream_path(current_user.stream) %></li>
              <% else %>
                <li><%= link_to 'Setup Stream', new_stream_path %></li>
              <% end %>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if current_user.stream %>
                    <li><%= link_to 'Publisher API', publish_path %></li>
                    <li><%= link_to 'Edit Stream', edit_stream_path(current_user.stream) %></li>
                  <% else %>
                    <li><%= link_to 'Setup Stream', new_stream_path %></li>
                  <% end %>
                  <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Logout', logout_path %></li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <li><%= link_to 'Sign In', new_user_session_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <div class="container">
      <% flash.each do |key, value| %>
            <div class="<%= flash_class(key) %>">
              <%= value %>
            </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>